services:
  db:
    image: postgres
    restart: no
    environment: 
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: zoo
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example_user -d journal"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  pgadmin:
    image: dpage/pgadmin4
    restart: no
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 127.0.0.1:7777:80